### ISSUE TITLE
Problème démarrage secmon.py

### ISSUE THREAD

**Issue by focheur91300** [Guezone/SECMON#21]
root@secmon:/# python3 /var/www/secmon/secmon.py
Traceback (most recent call last):
  File "/var/www/secmon/secmon.py", line 12, in <module>
    import cve_poller
  File "/var/www/secmon/cve_poller.py", line 12, in <module>
    import base64, os, smtplib, re, requests, time, sqlite3, feedparser, colorama, warnings
  File "/usr/local/lib/python3.9/dist-packages/feedparser.py", line 93, in <module>
    _base64decode = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'

**Comment by jheeree** [comment]
That error occurs because the "decodestring" function is deprecated. Now corresponds to "decodebyte" (ref: https://docs.python.org/3/library/base64.html).

The way I was able to fix it was changing directly in the library as follows:
`sed -i 's/base64.decodestring/base64.decodebytes/g' /usr/lib/python3/dist-packages/feedparser.py`

**Comment by alb-uss** [comment]
Hi ! @focheur91300, can you test the @jheeree workaround ? Thx :)

**Comment by focheur91300** [comment]
Hi ! @Guezone ,

The solution provided by @jheeree works.

The deferred path on my side.

`sed -i 's/base64.decodestring/base64.decodebytes/g' /usr/local/lib/python3.9/dist-packages/feedparser.py`

For info I am on docker der my side with the Dockerfile provided on Github.
